name: Push Docker Image to ECR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build -t practice ./proj

      - name: Tag Docker image
        run: |
          docker tag practice:latest \
            ${{ steps.login-ecr.outputs.registry }}/practice:latest

      - name: Push Docker image
        run: |
          docker push \
            ${{ steps.login-ecr.outputs.registry }}/practice:latest

      - name: Deploy to EC2
        run: |
          aws ssm send-command \
            --instance-ids "i-0ef44a9c329b12324" \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=[
              "aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 354780327224.dkr.ecr.ap-south-1.amazonaws.com",
              "docker pull 354780327224.dkr.ecr.ap-south-1.amazonaws.com/practice:latest",
              "docker stop practice-container || true",
              "docker rm practice-container || true",
              "docker run -d --name practice-container -p 80:80 354780327224.dkr.ecr.ap-south-1.amazonaws.com/practice:latest"
            ]' \
            --region ap-south-1