name: dependency job 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened,closed]
jobs:
  job1:
     runs-on: ubuntu-latest
     steps:
      - name: checkoutcode
        uses: actions/checkout@v3
        run: ls -la
  job2: 
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: job2 started
        run: echo "job2 started"
  job3:
    needs: [job1, job2]
    runs-on: ubuntu-latest
    steps:
      - name: job3 started
        run: echo "job3 started"
      
