name: node 
on: 
  workflow_dispatch:
      inputs:
        node-version:
          description: 'Node.js version'
          required: true
          default: '20'
jobs:
node:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
