name: parallel

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: job1 started
        run: echo "job1 started"

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: job2 started
        run: echo "job2 started"

  job3:
    runs-on: ubuntu-latest
    steps:
      - name: job3 started
        run: echo "job3 started"
