name: Self Hosted Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Check runner
        run: |
          echo "Hello from EC2"
          hostname
          whoami
          pwd
